config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'campgrounds#index'

  resources :users, only: [:new, :create] do
    resources :contributor_applications, only: [:new, :create, :update], shallow: true
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :campgrounds do
    resources :comments, except: [:index, :show, :new, :edit], shallow: true
    resources :impressions, except: [:show, :index, :destroy], shallow: true
  end
  get '/login', to: 'sessions#new'
  get '/admin', to: 'users#admin', as: :admin

end

app/models/user.rb
class User < ApplicationRecord
  has_many :campgrounds, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :impressions, dependent: :destroy
  has_many :contributor_applications, dependent: :destroy

  has_attached_file :image, styles: { medium: "500x500>", thumb: "100x100>" }, presence: true, default_url: "https://i.imgur.com/KyKTnXJ.jpg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  has_secure_password
  validates :email, presence: true, uniqueness: true, on: :create
  validates :password, length: { minimum: 6 }, on: :create

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_admin, only: [:admin]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "You have succesfully signed up!"
      redirect_to root_path
    else
      render :new
    end
  end

  def admin
    @pending_contributor_applications = ContributorApplication.where(pending: true)
  end

private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :image)
  end

  def authorize_admin
    redirect_to root_path if current_user.nil? || !current_user.admin
  end
end

app/views/users/admin.html.erb
<div class="container">
  <div class="row">
    <h1>Pending Contributor Applications</h1>
  </div> 
  <div class="row">
    <table class="col s12 highlight responsive-table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Essay</th>
          <th>Decision</th>
        </tr>
      </thead>
      <tbody>
        <% @pending_contributor_applications.each do |app| %>
          <tr>
            <td><%= app.user.full_name %></td>
            <td><%= simple_format(app.content) %></td>
            <td>
              <%= link_to "Accept", contributor_application_path(app, approved: "yes"), method: :put, class: "btn waves-effect waves-light green" %>
              <%= link_to "Deny", contributor_application_path(app, approved: "no"), method: :put, class: "btn waves-effect waves-light red" %>
            </td>
          </tr>    
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <h1>Sign Up!</h1>
  </div>
  <div class="row">    
    <%= form_for @user, html: { multipart: true }, class: "col s12" do |f| %>
     <div class="row">
        <% if @user.errors.any? %>
          <blockquote class="error_messages col s12">
            <ul>  
              <% for message in @user.errors.full_messages %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </blockquote>
        <% end %>
      </div> 
      <div class="row">
        <div class="input-field col s6">
        <%= f.text_field :first_name, required: true %>
        <%= f.label :first_name %>
        </div>
        <div class="input-field col s6">
        <%= f.text_field :last_name, required: true %>
        <%= f.label :last_name %>
        </div>
      </div> 
      <div class="row">
        <div class="input-field col s12">
        <%= f.email_field :email, required: true, class: "validate" %>
        <%= f.label :email, 'data-error' => 'Not a valid email address' %>
        </div>
      </div> 
      <div class="row">
        <div class="input-field col s12">
        <%= f.password_field :password, required: true, minlength: "6" %>
        <%= f.label :password %>
        </div>
      </div> 
      <div class="row">
        <div class="input-field col s12">
        <%= f.password_field :password_confirmation, required: true %>
        <%= f.label :password_confirmation %>
        </div>
      </div>
      <div class="row">
        <div class="input-field file-field col s12">
          <div class="btn">
            <span>Profile Photo</span>
            <%= f.file_field :image %>
          </div>
          <div class="file-path-wrapper">
            <input class="file-path validate" type="text" placeholder="Upload a profile photo">
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col s12">
          <button class="btn-large waves-effect waves-light blue-grey" type="submit" name="action">Sign Up
            <i class="material-icons right">send</i>
          </button>
        </div>
      </div>
    <% end %> 
  </div>
</div>