config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'campgrounds#index'

  resources :users, only: [:new, :create] do
    resources :contributor_applications, only: [:new, :create, :update], shallow: true
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :campgrounds do
    resources :comments, except: [:index, :show, :new, :edit], shallow: true
    resources :impressions, except: [:show, :index, :destroy], shallow: true
  end
  get '/login', to: 'sessions#new'
  get '/admin', to: 'users#admin', as: :admin

end

app/models/campground.rb
class Campground < ApplicationRecord
  belongs_to :user

  has_many :campground_images, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :impressions, dependent: :destroy

  def count_impressions_totals
    { clean_yes: self.impressions.where(clean: 1).count,
      clean_no: self.impressions.where(clean: -1).count,
      crowded_yes: self.impressions.where(crowded: 1).count,
      crowded_no: self.impressions.where(crowded: -1).count,
      shade_yes: self.impressions.where(shade: 1).count,
      shade_no: self.impressions.where(shade: -1).count,
      privacy_yes: self.impressions.where(privacy: 1).count,
      privacy_no: self.impressions.where(privacy: -1).count,
      fire_yes: self.impressions.where(fire: 1).count,
      fire_no: self.impressions.where(fire: -1).count
    }
  end
end

app/controllers/campgrounds_controller.rb
class CampgroundsController < ApplicationController
  before_action :authorize, except: [:index, :show]
  before_action :authorize_edit, only: [:edit, :update, :destroy]
  before_action :authorize_contributor, except: [:index, :show]

  def index
    @campgrounds = Campground.all.reverse
    @campground = Campground.new
  end

  def show
    @campground = Campground.find(params[:id])
    @comment = Comment.new
  end

  def new
    @campground = Campground.new
  end

  def create
    @campground = Campground.new(campground_params)
    @campground.user = current_user
    if @campground.save
      params[:images].each { |image| @campground.campground_images.create(image: image) } if params[:images]
      @campground.campground_images.first.update_attributes(main_image: true) if params[:images]
      redirect_to campgrounds_path
    else
      render :new
    end
  end

  def edit
    @campground = Campground.find(params[:id])
  end

  def update
    @campground = Campground.find(params[:id])

    if @campground.update_attributes(campground_params)
      params[:images].each { |image| @campground.campground_images.create(image: image) } if params[:images]

      @campground.campground_images.find_by(main_image: true).update_attributes(main_image: nil)
      CampgroundImage.find(params[:main_image]).update_attributes(main_image: true)

      if params[:remove]
        params[:remove].each do |id|
          CampgroundImage.find(id).destroy if !CampgroundImage.find(id)[:main_image]
        end
      end

      redirect_to campground_path(params[:id])
    else
      render :edit
    end
  end

  def destroy
    @campground = Campground.find(params[:id])
    @campground.destroy
    redirect_to campgrounds_path
  end

private

  def campground_params
    params.require(:campground).permit(:title, :content, :image)
  end

  def authorize_contributor
    redirect_to root_path if !current_user.contributor
  end

  def authorize_edit
    redirect_to campground_path(params[:id]) if current_user != Campground.find(params[:id]).user
  end
end

app/views/campgrounds/edit.html.erb
<div class="container">
  <div class="row">
    <h1>Edit <%= @campground.title %></h1>
  </div>
  <div class="row">
    <%= form_for @campground, class: "col s12", html: { multipart: true } do |f| %>
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :title %>
          <%= f.label :title, class: "active" %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_area :content, class: "materialize-textarea" %>
          <%= f.label :content, class: "active" %>
        </div>
      </div>
      <div class="row">
        <div class="col s6">
          <%= f.label "Change main image" %>
          <div class="divider"></div>
        </div>
        <div class="col s6">
          <%= f.label "Select images to delete - you cannot delete main image"%>
          <div class="divider"></div>
        </div>
      </div>  
      <div class="row">
        <div class="col s6">
          <% @campground.campground_images.each do |campground_image| %>
            <p class="col s12">  
              <%= radio_button_tag :main_image, campground_image[:id], campground_image[:main_image] %>
              <%= f.label :main_image, for: "main_image_#{campground_image.id}" do %>
                <%= image_tag campground_image.image.url(:thumb) %>
              <% end %>
            </p>
          <% end %>
        </div>
        <div class="col s6">
          <% @campground.campground_images.each do |campground_image| %>
            <p class="col s12">  
              <%= check_box_tag "remove[]", campground_image[:id], false, :id => "remove_#{campground_image.id}" %>
              <%= f.label "remove[]", for: "remove_#{campground_image.id}" do %>
                <%= image_tag campground_image.image.url(:thumb) %>
              <% end %>
            </p>
          <% end %>
        </div>
      </div>
      <div class="row">
        <%= f.label "Add photos", class: "col s12" %>
      </div>
      <div class="divider"></div>  
      <div class="row">
        <div class="input-field file-field col s12">
          <div class="btn">
            <span>Select Images</span>
            <%= file_field_tag "images[]", type: :file, multiple: true %>
          </div>
          <div class="file-path-wrapper">
            <input class="file-path validate" type="text" placeholder="Upload one or more files">
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col s3">
          <button class="btn-large waves-effect waves-light green" type="submit" name="action">Edit
            <i class="material-icons right">mode_edit</i>
          </button>
        </div>
        <div class="col s3">
          <%= link_to campground_path(@campground), class: "btn-large waves-effect waves-light red" do %>
            Cancel<i class="material-icons right">cancel</i>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/campgrounds/index.html.erb
<% @campgrounds.each do |campground| %>
  <div class="parallax-container">
    <div class="parallax"><%= image_tag campground.campground_images.find_by(main_image: true).image.url(:parallax) %></div>
  </div>
  <div class="section white">
    <div class="row container">
      <h3 class="header"><%= campground.title %></h3>
      <p class="grey-text"><%= truncate(campground.content, length: 1000, separator: ' ') %></p>
      <%= link_to "Read more!", campground_path(campground), class: "waves-effect waves-teal btn-flat" %>
    </div>
  </div>
<% end %>

<% if !current_user.nil? && current_user.contributor %>
  <div class="fixed-action-btn">
    <%= link_to new_campground_path, class: "btn-floating btn-large modal-trigger blue-grey darken-2" do %>
      <i class="large material-icons">add</i>
    <% end %>
  </div>
<% end %>

<script>
  $(document).ready(function(){
      $('.parallax').parallax();
  });
</script>

app/views/campgrounds/new.html.erb
<div class="container">
  <div class="row">
    <h1>Create a new campground!</h1>
  </div>
  <div class="row">
    <%= form_for @campground, class: "col s12", html: { multipart: true } do |f| %>
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :title, required: true %>
          <%= f.label :title, class: "active" %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_area :content, class: "materialize-textarea", required: true %>
          <%= f.label :content, class: "active" %>
        </div>
      </div>
      <div>
      <div class="row">
        <%= f.label "Add photos", class: "col s12" %>
      </div>
      <div class="divider"></div>  
      <div class="row">
        <div class="input-field file-field col s12">
          <div class="btn">
            <span>Select Images</span>
            <%= file_field_tag "images[]", type: :file, multiple: true, required: true %>
          </div>
          <div class="file-path-wrapper">
            <input class="file-path validate" type="text" placeholder="Upload one or more files">
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col s12">
          <button id ="create-campground" class="btn-large waves-effect waves-light blue-grey" type="submit" name="action">Create Campground!</button>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/campgrounds/show.html.erb
<div class="container">
  <div class="row valign-wrapper">
    <div class="col s8">      
      <h1><%= @campground.title %></h1>
    </div>
    <div class="col s4">
      <%= link_to "Back to all Campgrounds", campgrounds_path, class: "waves-effect waves-light btn blue-grey" %>
    </div>
  </div>
  <div class="row">
    <div class="col s12">
      <%= image_tag @campground.campground_images.find_by(main_image: true).image.url, class: "materialboxed responsive-img" %>
    </div>
  </div>
  <div class="row">
    <% @campground.campground_images.where(main_image: nil).each do |campground_image| %>
      <div class="col s2">
        <%= image_tag campground_image.image.url, class: "materialboxed responsive-img" %>
      </div>
    <% end %>
  </div>
  <div class="row">
    <h5>By <%= @campground.user.full_name %></h5>
    <p class="flow-text"><%= simple_format(@campground.content) %></p>
  </div>
  <div class="divider"></div>
  <div class="row valign-wrapper">
    <div class="col s8">
     <h3>Impressions</h3>
    </div>
    <% if !current_user.nil? %>
      <% if current_user.impressions.find_by(campground_id: @campground) %>
        <div class="col s4">
          <%= link_to "Edit your impression!", edit_impression_path(current_user.impressions.find_by(campground_id: @campground)), class: "waves-effect waves-light btn blue-grey" %>
        </div>
      <% else %>
        <div class="col s4">
          <%= link_to "Provide your impression!", new_campground_impression_path(@campground), class: "waves-effect waves-light btn blue-grey" %>
        </div>
      <% end %>
    <% end %>
  </div>
  <% if @campground.impressions.empty? %>
    <div class="row">
      <h4 class="col s12">No impressions submitted yet, be the first!</h4>
    </div>
  <% else %>
  <% @counts = @campground.count_impressions_totals %>
    <div class="row">
      <div class="col s4 blue-grey lighten-2 center-align">
        <div class="row legend">
          <h5 id="legend" class="col s12">LEGEND</h5>
        </div>
        <div id="yes-legend" class="row legend">
          <h5 class="col s12">YES</h5>
        </div>
        <div id="no-legend" class="row legend">
          <h5 class="col s12">NO</h5>
        </div>
      </div>
      <div class="col s4">
        <div class="row">
          <h5 class="col s12">Clean?</h5>
        </div>
        <div class="row">
          <div class="ct-chart ct-golden-section col s12" id="chart1"></div>
        </div>
      </div>
      <div class="col s4">
        <div class="row">
          <h5 class="col s12">Crowded?</h5>
        </div>
        <div class="row">
          <div class="ct-chart ct-golden-section col s12" id="chart2"></div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col s4">
        <div class="row">
          <h5 class="col s12">Private?</h5>
        </div>
        <div class="row">
          <div class="ct-chart ct-golden-section col s12" id="chart3"></div>
        </div>
      </div>
      <div class="col s4">
        <div class="row">
          <h5 class="col s12">Shaded?</h5>
        </div>
        <div class="row">
          <div class="ct-chart ct-golden-section col s12" id="chart4"></div>
        </div>
      </div>
      <div class="col s4">
        <div class="row">
          <h5 class="col s12">Fires OK?</h5>
        </div>
        <div class="row">
          <div class="ct-chart ct-golden-section col s12" id="chart5"></div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="divider"></div>
  <div class="row">
    <h3 class="col s12">Comments</h3>
  </div>
  <% @campground.comments.each do |comment| %>
    <div class="divider"></div>
    <div class="row section">
      <div class="col s3">
        <div class="chip">
          <%= image_tag comment.user.image.url(:thumb), alt: "Contact Person" %>
          <%= comment.user.full_name %>
        </div>        
      </div>
      <div class="col s7">
        <p><%= simple_format(comment.content) %></p>
      </div>
      <% if current_user == comment.user %>
        <div class="col s1">
          <a id="<%= "comment-#{comment.id}" %>" class="btn-floating green"><i class="material-icons">mode_edit</i></a>
        </div>
        <div class="col s1">
          <button data-target="delete-comment-modal" class="modal-trigger btn-floating red darken-1"><i class="material-icons">delete</i></button>
        </div>
      <% end %>
    </div>
    <% if current_user == comment.user %>
      <div id="<%= "edit-comment-#{comment.id}" %>" class="row" style="display:none;">
        <%= form_for comment, class: "col s12" do |f| %>
          <div class="row valign-wrapper">
            <div class="input-field col s10">
              <%= f.text_area :content, class: "materialize-textarea", required: true %>
              <%= f.label :content, "Comment text", class: "active" %>
            </div>
            <div class="col s2">
              <button class="btn waves-effect waves-light col s12 green" type="submit" name="action">Edit
                <i class="material-icons right">mode_edit</i>
              </button>
            </div>
          </div>
        <% end %>
      </div>
      <div id="delete-comment-modal" class="modal">
        <div class="modal-content">
          <h4>Are you sure you want to delete this comment?</h4>
        </div>
        <div class="modal-footer">
          <button class="modal-action modal-close waves-effect waves-green btn-flat ">No</button>
          <%= link_to "Yes", comment_path(comment), method: :delete, class: "modal-action modal-close waves-effect waves-red btn-flat" %>
        </div>
      </div>
    <% end %>
  <% end %>
  <div class="divider"></div>
  <% if !current_user.nil? %>
    <div class="row">
      <%= form_for [@campground, @comment], class: "col s12" do |f| %>
        <div class="row valign-wrapper">
          <div class="input-field col s10">
            <%= f.text_area :content, class: "materialize-textarea", required: true %>
            <%= f.label :content, "Write your comment here..." %>
          </div>
          <div class="col s2">
            <button class="btn waves-effect waves-light col s12 blue-grey" type="submit" name="action">Comment</button>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<% if current_user == @campground.user %>
  <div class="fixed-action-btn">
    <a class="btn-floating btn-large blue-grey darken-2">
      <i class="large material-icons">menu</i>
    </a>
    <ul>
      <li>
        <%= link_to edit_campground_path, class: "btn-floating green" do %>
          <i class="material-icons">mode_edit</i>
        <% end %>
      </li>
      <li>
        <button data-target="delete-modal" class="modal-trigger btn-floating red darken-1"><i class="material-icons">delete</i></button>
      </li>
    </ul>
  </div>
  <div id="delete-modal" class="modal">
    <div class="modal-content">
      <h4>Are you sure you want to delete this campground?</h4>
    </div>
    <div class="modal-footer">
      <button class="modal-action modal-close waves-effect waves-green btn-flat ">No</button>
      <%= link_to "Yes", campground_path(@campground), method: :delete, class: "modal-action modal-close waves-effect waves-red btn-flat" %>
    </div>
  </div>
<% end %>

<script>
  $(document).ready(function(){
    $('.materialboxed').materialbox();
    $('.modal').modal();

    <% if !@campground.impressions.empty? %>
      var yesImpressions = <%= [@counts[:clean_yes], @counts[:crowded_yes], @counts[:privacy_yes], @counts[:shade_yes], @counts[:fire_yes]] %>;
      var noImpressions = <%= [@counts[:clean_no], @counts[:crowded_no], @counts[:privacy_no], @counts[:shade_no], @counts[:fire_no]] %>;

      var sums = [];
      for (var i = 0; i < yesImpressions.length; i++) {
        sums.push(2 * (yesImpressions[i] + noImpressions [i]));
      };

      var yesLabels = [];
      yesImpressions.forEach(function(yesImpression) {
        yesImpression === 0? yesLabels.push(' ') : yesLabels.push(yesImpression.toString());
      });

      var noLabels = [];
      noImpressions.forEach(function(noImpression) {
        noImpression === 0? noLabels.push(' ') : noLabels.push(noImpression.toString());
      });

      console.log(yesLabels)

      new Chartist.Pie('#chart1', {
        labels: [yesLabels[0], noLabels[0]],
        series: [yesImpressions[0], noImpressions[0]]
      }, {
        donut: true,
        donutWidth: 30,
        startAngle: 270,
        total: sums[0],
        showLabel: true
      });
      new Chartist.Pie('#chart2', {
        labels: [yesLabels[1], noLabels[1]],
        series: [yesImpressions[1], noImpressions[1]]
      }, {
        donut: true,
        donutWidth: 30,
        startAngle: 270,
        total: sums[1],
        showLabel: true
      });
      new Chartist.Pie('#chart3', {
        labels: [yesLabels[2], noLabels[2]],
        series: [yesImpressions[2], noImpressions[2]]
      }, {
        donut: true,
        donutWidth: 30,
        startAngle: 270,
        total: sums[2],
        showLabel: true
      });
      new Chartist.Pie('#chart4', {
        labels: [yesLabels[3], noLabels[3]],
        series: [yesImpressions[3], noImpressions[3]]
      }, {
        donut: true,
        donutWidth: 30,
        startAngle: 270,
        total: sums[3],
        showLabel: true
      });
      new Chartist.Pie('#chart5', {
        labels: [yesLabels[4], noLabels[4]],
        series: [yesImpressions[4], noImpressions[4]]
      }, {
        donut: true,
        donutWidth: 30,
        startAngle: 270,
        total: sums[4],
        showLabel: true
      });
    <% end %> 

    $("[id^=comment-]").click(function(evt) {
      $(`#edit-${evt.currentTarget.id}`).toggle()
    });  
  });
</script>