config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'campgrounds#index'

  resources :users, only: [:new, :create] do
    resources :contributor_applications, only: [:new, :create, :update], shallow: true
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :campgrounds do
    resources :comments, except: [:index, :show, :new, :edit], shallow: true
    resources :impressions, except: [:show, :index, :destroy], shallow: true
  end
  get '/login', to: 'sessions#new'
  get '/admin', to: 'users#admin', as: :admin

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CampShare</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="navbar-fixed">
        <nav>
          <div class="nav-wrapper  blue-grey darken-4">
            <div class="container">
              <a href="/" class="brand-logo left"><img src="https://i.imgur.com/J9p032Q.png"></a>
              <ul id="nav-mobile" class="right">
                <% if current_user %>
                  <li>Welcome, <%= current_user.first_name %>&nbsp;</li>
                  <% if !current_user.contributor %>
                    <% if !current_user.contributor_applications.empty? && current_user.contributor_applications.last.pending %>
                      <li>&nbsp;Contributor Status: Pending</li>
                    <% else %>
                      <li><%= link_to 'Become a contributor!', new_user_contributor_application_path(current_user) %></li>
                    <% end %>
                  <% end %>
                  <li><%= link_to 'Log Out', session_path('dummy'), method: :delete %></li>
                <% else %>
                  <li><%= link_to 'Log In', login_path %></li>
                  <li><%= link_to 'Sign Up', new_user_path %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </nav>
      </div>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer class="page-footer blue-grey darken-4">
      <div class="footer-copyright">
        <div class="container">
        © 2017 Nedim Filipovic
        <div class="right">Icons made by <a href="https://www.flaticon.com/authors/vectors-market" title="Vectors Market" class="grey-text text-lighten-4">Vectors Market</a> from <a href="https://www.flaticon.com/" title="Flaticon" class="grey-text text-lighten-4">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank" class="grey-text text-lighten-4">CC 3.0 BY</a></div>
        </div>
      </div>
    </footer>
  </body>
</html>